spring:
  application:
    name: Product Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

jpa:
  database-platform:
    dialect: org.hibernate.dialect.PostgreSQLDialect
  show-sql: true
